$schemaver: '2.0'
repo_url: https://github.com/byu-oit/cas-mfa
software:
  - name: cas-mfa
    type: Web App
    aliases:
    short_description:
    assignment_group: gro:AD-Identity and Access Management
    notes:
    maintained_by:
      - fcsdbm
    developed_by_byu: true
    ddd:
      business_domain:
      ubiquitous_language_url:
      context_map_url:
    links:
      system_documentation_url:
      swagger_urls:
    microservice: false
    technologies_used:
      - Travis-ci.com
      - Java
      - JavaScript
      - Shell
      - Batchfile
      - Groovy
      - Maven
    stages:
      production:
        urls:
          product_page:
          physical_url:
          virtual_url:
        hosting_location: BYU
        aws_account:
        relationships:
          depends_on:
            db_read_write:
            db_read_only:
            software:
              - CAS (Central Authentication Service)
          supports:
            software:
            service:
          reverse_proxy:
          runs_on:
            server_cluster:
            virtual_server:
            rack_server:
            blade_server:
    tags:
      data-sensitivity: confidential
      team: AD-Identity and Access Management
      app: cas-mfa
